# Generated by Django 4.2.10 on 2024-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('venue', models.CharField(max_length=200)),
                ('venue_location', models.CharField(max_length=200)),
                ('event_details', models.TextField(default='Description of this event is not available')),
                ('banner', models.ImageField(upload_to='banner_images/')),
            ],
        ),
    ]
