# Generated by Django 4.2.10 on 2024-02-18 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somtuEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 22, 8, 22, 834947)),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='banner',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
