# Generated by Django 5.0.2 on 2024-02-20 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somtuEvents', '0002_eventdetails_event_date_eventdetails_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='event_date',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 22, 2, 21, 134509)),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 21, 2, 21, 134509)),
        ),
    ]
