# Generated by Django 5.0.2 on 2024-02-20 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somtuEvents', '0004_alter_eventdetails_event_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=200)),
                ('attendee_email', models.EmailField(max_length=100)),
                ('attendee_phone', models.CharField(max_length=20)),
                ('attendee_class', models.CharField(max_length=30)),
                ('is_somtu_student', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 22, 9, 7, 566964)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 21, 9, 7, 566964)),
        ),
    ]
