# Generated by Django 5.0.2 on 2024-02-20 16:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somtuEvents', '0008_alter_eventdetails_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='somtuEvents.eventdetails'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 23, 27, 14, 620412)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 22, 27, 14, 620412)),
        ),
    ]
