# Generated by Django 5.0.2 on 2024-02-21 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somtuEvents', '0009_eventattendee_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 22, 11, 12, 125768)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 21, 11, 12, 125768)),
        ),
    ]
