# Generated by Django 5.0.2 on 2024-02-22 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somtuEvents', '0010_alter_eventdetails_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 9, 54, 47, 615244)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 8, 54, 47, 615244)),
        ),
    ]
