# Generated by Django 5.0.2 on 2024-02-22 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somtuEvents', '0011_alter_eventdetails_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 22, 42, 55, 971716)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 21, 42, 55, 971716)),
        ),
    ]
